apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookie
  name: cookie-app-healthcheck
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cookie
