apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cookie-app-healthcheck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cookie
    spec:
      containers:
      - name: webapp
        image: "quay.io/coreos/example-app:v1.0"
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
