apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookie
  name: cookie-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cookie-app
