apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookie
  name: cookie-app-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
    targetPort: 80
  selector:
    app: cookie-app
