apiVersion: v1
kind: Pod
metadata:
  name: cookie-app
  labels:
    app: cookie-app
spec:
  containers:
  - name: cookie-app
    image: quay.io/coreos/example-app:v1.0
    ports:
    - containerPort: 80
