apiVersion: v1
data:
  prometheus.yaml: ewogICAgYXBpVmVyc2lvbjogMSwKICAgIGRhdGFzb3VyY2VzOiBbCiAgICAgICAgewogICAgICAgICAgICBhY2Nlc3M6IHByb3h5LAogICAgICAgICAgICBlZGl0YWJsZTogZmFsc2UsCiAgICAgICAgICAgIG5hbWU6IHByb21ldGhldXMsCiAgICAgICAgICAgIG9yZ0lkOiAxLAogICAgICAgICAgICB0eXBlOiBwcm9tZXRoZXVzLAogICAgICAgICAgICB1cmw6IGh0dHA6Ly9wcm9tZXRoZXVzLm1vbml0b3Jpbmcuc3ZjOjkwOTAsCiAgICAgICAgICAgIHZlcnNpb246IDEKICAgICAgICB9CiAgICBdCn0=
kind: Secret
metadata:
  name: grafana-datasources
  namespace: monitoring
type: Opaque